### ISSUE TITLE
Add parameter or hash to a route

### ISSUE THREAD

**Issue by avi-getctrl** [zilch/type-route#107]
When you have an existing route, and you want to change it (for example: to add or remove a hash parameter), It's quite difficult right now.

This is my current solution, but it's far of being good:
```
export function getRouteByNameWithFallback(name: string) {
  for (const [routeName, route] of Object.entries(routes)) {
    if (routeName === name) return route;
  }
  return routes.home;
}

interface AddRouteParamsArgs {
  route: MaybeAppRoute;
  newParams: Record<string, string>;
}

export function addRouteParams({ route, newParams }: AddRouteParamsArgs) {
  const params = route ? { ...route.params } : null;
  const routeName = route?.name;
  const routeBuilder = getRouteByNameWithFallback(routeName ? routeName : '');
  try {
    // @ts-ignore -- The param type can't be fulfilled, as it has conflicting definitions.
    return routeBuilder({ ...params, ...newParams });
  } catch (e) {
    console.warn('Failed to add route param:', { route, newParams, routeBuilder, e });
    return null;
  }
}

interface removeRouteParamArgs {
  route: MaybeAppRoute;
  paramName: string;
}

export function removeRouteParam({ route, paramName }: removeRouteParamArgs) {
  const routeName = route?.name;
  const routeBuilder = getRouteByNameWithFallback(routeName ? routeName : '');
  const params = route ? { ...route.params } : null;
  if (!params) return null;
  // @ts-ignore -- The param type can't be fulfilled, as it has conflicting definitions.
  delete params?.[paramName];

  try {
    // @ts-ignore -- The param type can't be fulfilled, as it has conflicting definitions.
    return routeBuilder(params);
  } catch (e) {
    console.warn('Failed to remove route param:', { route, paramName, e });
    return null;
  }
}

```

**Comment by seivan** [comment]
If you are dynamically adding paths, you should be using a trailing wildcard.

If you are dynamically adding k/v combinations in query params (I am guessing this is your case) then you really ought to write your own serializer. 

What you're doing seems... wrong? 

> When you have an existing route, and you want to change it (for example: to add or remove a hash parameter), It's quite difficult right now.

You shouldn't be adding or removing your url params. 
You should be setting your URL params with the changes you're expecting declaratively. 
Store the transient state of addition/removal elsewhere (mobx,redux, useState). 
Alter you query params to an acceptable state, then let your serializer deal with it. 

If it's a value you want to parse into an existing type, use [`ValueSerializer`](https://zilch.dev/type-route/docs/api-reference/types/value-serializer).
If you want to map an entire custom composition of types into query params (and back) you might want to look into [`QueryStringSerializer`](https://zilch.dev/type-route/docs/guides/custom-query-string).
However, I strongly suggest trying to make it work with `ValueSerializer` first.

**Comment by bradenhs** [comment]
Hi @avi-getctrl! Thanks for opening this issue! Are you able to share a more complete example of how you're using these helper functions you've created? I'd like to understand your use case better.

**Comment by avi-getctrl** [comment]
I want that a dialog would be displayed when navigating to `someurl.com/everyParamsHere?querystring=anything&dialog=true`, and it should removed when the dialog is closed (The location should go back to someurl.com/everyParamsHere?querystring=anything).
I don't speak about how to show the dialog, and how to navigate when closing it, of course. This is the JS part.
I mean how I get the URL with the dialog querystring from the current route, that I get from the router listener.
And then - how to remove only this part of the querystring, and return from the dialog added route, to the original route.

**Comment by bradenhs** [comment]
Here's a way to do this today. It isn't quite perfect but I believe it'd be sufficient for your use case:

```ts
const { routes, session } = createRouter({
   ...
});

function closeDialog(route: Route<typeof routes>) {
  const url = new URL(route.href);
  url.searchParams.delete("dialog");
  session.replace(url.href);
}
```

The `session` object Type Route provides can be good in scenarios like this where you need to be a bit more dynamic in your routing.

---

A method called something like `modify` on the route object might be a good way to make this more ergonomic in the future. This api doesn't exist yet but maybe one day I'll add something like it thanks to your input!

```ts
function closeDialog(route: Route<typeof route>) {
  route.modify(({ ...params, dialog: _ }) => params).replace()
}
```

**Comment by bradenhs** [comment]
Also if you want a `dialog` property to be on every single route in your application you may consider defining your routes in this manner:

```ts
const base = defineRoute(
  {
    dialog: param.query.optional.boolean,
  },
  () => "/"
);

const { routes, session } = createRouter({
  foo: base.extend("/foo"),
  bar: base.extend(
    {
      baz: param.query.string,
    },
    () => "/bar"
  ),
});
```

**Comment by avi-getctrl** [comment]
> Here's a way to do this today. It isn't quite perfect but I believe it'd be sufficient for your use case:
> 
> ```ts
> const { routes, session } = createRouter({
>    ...
> });
> 
> function closeDialog(route: Route<typeof routes>) {
>   const url = new URL(route.href);
>   url.searchParams.delete("dialog");
>   session.replace(url.href);
> }
> ```
> 
> The `session` object Type Route provides can be good in scenarios like this where you need to be a bit more dynamic in your routing.
> 
> A method called something like `modify` on the route object might be a good way to make this more ergonomic in the future. This api doesn't exist yet but maybe one day I'll add something like it thanks to your input!
> 
> ```ts
> function closeDialog(route: Route<typeof route>) {
>   route.modify(({ ...params, dialog: _ }) => params).replace()
> }
> ```

Thank you!

The `modify` method can be very useful, but it should have also the ability to delete optional parameters, and not only modify or add them.
