### ISSUE TITLE
Removing the Beta

### ISSUE THREAD

**Issue by garronej** [zilch/type-route#114]
Hello,  
How about removing the Beta and warnings from the readme?  
It would help me convice teams to use `type-route`.  

Best,

**Comment by bradenhs** [comment]
Thanks for pushing on this! I've been using Type Route actively in my own projects since first creating it and as of late haven't needed to make any big changes/fixes to the library so I'd say its pretty stable. I'll find some time beginning of next week to 1.0 it.

**Comment by rencarKTR** [comment]
btw this lib is actually better than react-router on so many levels 👍

**Comment by garronej** [comment]
Great thanks!
