### ISSUE TITLE
Use functions as parameters

### ISSUE THREAD

**Issue by ERivierePEReN** [zilch/type-route#135]
Hello,

I wondered if it was possible to pass down functions as parameters?

I tried to tinker around `param.state.ofType` with no success.

Thank you so much for your help and your work!

**Comment by bradenhs** [comment]
It isn't possible to pass functions as parameters. I'm curious about your exact use case. Would you mind giving a few more details? I might be able to give a better answer with some more information.

**Comment by ERivierePEReN** [comment]
Thank you for your quick reply.

I am migrating a project towards the stack that our team uses. It's an project that did not have the best coding practices but it's archived so I'm trying to not rewrite everything.

The way things were is that a menu would lead to a visualization tool on a different page. One of the parameters was a function that would take care of generating the data for the graphs. I assume the choice to pass down functions as parameters was because the whole logic would be different depending on the menu selected.

I could probably rewrite some parts of the code so that it runs before routing to the new page and use an object as the parameters. I just thought it would be quicker and easier to keep as much of the old project as I could.

**Comment by bradenhs** [comment]
Got it. Everything in the URL needs to be serializable so it can be persisted and functions aren't (easily) serializable. Do those pages which take functions as a parameter work after refreshing? If so, I imagine somehow that that information can be serialized. For instance, if there are a finite set of predetermined functions you can have a map between a set of strings and the actual function. Then the string key gets put into the url and you use that to look up the desired function.

**Comment by ERivierePEReN** [comment]
The parameters were indeed not serialized. While definitely not a best case scenario, I feel like information does not have to be persistent, particularly when using state (instead of path or query)? 

But I agree with you it would be cleaner to rework that code a bit to generate the data and pushing it to the router instead of pushing functions :)

**Comment by bradenhs** [comment]
For what it's worth state parameters are actually persisted and need to be serializable. They just don't appear in the users URL. They are stored in the browser history though.

Regardless, if needing the page to look the same after a refresh isn't a requirement you could have some separate global store where you could put the function you intend to use on the next page. Then you could navigate to the next page and retrieve the stored function. Again, not ideal but this could be a good work around for your situation. Just an idea :) Good luck figuring it out!

**Comment by ERivierePEReN** [comment]
Indeed, there are definitely ways to make it work even if they're not ideal.

Thank you again for your time, I really appreciate it!
