### ISSUE TITLE
Sitemap generation

### ISSUE THREAD

**Issue by elderapo** [zilch/type-route#86]
Would be cool if it was possible to generate [sitemap](https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap) so it can be supplied to google for correct indexing of the page :) I guess it could be an optional webpack plugin that generates sitemap file next to the build artifacts.

**Comment by bradenhs** [comment]
I don't have much experience with this but would be happy to accept a PR!

**Comment by garronej** [comment]
@thieryw this could be a quick win.  
Forking from [our plugin for typeroute](https://github.com/garronej/github-pages-plugin-for-type-route) we could get this implemented in a couple of hours.

**Comment by bradenhs** [comment]
Just updated the Type Route website (https://type-route.zilch.dev/) and was looking into this. Reading some docs it appears that a sitemap wouldn't make a difference in the case of this project: https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview?hl=en&ref_topic=4581190&visit_id=638082056476728778-2506658020&rd=1#do-i-need-a-sitemap. Let me know if I'm missing anything. Happy to reopen this if so!
